export const WORLD_WIDTH = 12000;
export const WORLD_HEIGHT = 12000;

export const PLAYER_MAX_SPEED = 500;
export const PLAYER_ACCELERATION = 900;
export const PLAYER_DRAG = 650;
export const PLAYER_ROTATION_SMOOTHING = 14;
export const PLAYER_COLLISION_RADIUS = 58;
export const PLAYER_MAX_HEALTH = 100;
export const PLAYER_HEALTH_REGEN_PER_SECOND = 1;
export const PLAYER_RESPAWN_DELAY_MS = 2000;
export const PLAYER_RESPAWN_INVULNERABILITY_MS = 2000;

export const PROJECTILE_SPEED = 1200;
export const PROJECTILE_LIFETIME_MS = 1200;
export const FIRE_COOLDOWN_MS = 180;
export const PROJECTILE_POOL_SIZE = 48;
export const PROJECTILE_COLLISION_RADIUS = 18;

export const CAMERA_LERP = 0.12;
export const CAMERA_ZOOM = 0.86;

export const PLAYER_SPAWN_X = 760;
export const PLAYER_SPAWN_Y = 760;

export const MAP_PADDING = 520;
export const BASE_RADIUS = 340;
export const CENTRAL_ZONE_RADIUS = 720;
export const GRID_STEP = 1000;

export const ASTEROID_ZONE_WIDTH = 2400;
export const ASTEROID_ZONE_HEIGHT = 1800;
export const ASTEROID_MAX_COUNT = 15;

export const ASTEROID_MIN_RADIUS = 45;
export const ASTEROID_MAX_RADIUS = 75;
export const ASTEROID_MAX_HEALTH = 100;
export const ASTEROID_PROJECTILE_DAMAGE = 15;
export const ASTEROID_COLLISION_DAMAGE = 10;

export const ASTEROID_RESPAWN_MIN_MS = 5000;
export const ASTEROID_RESPAWN_MAX_MS = 15000;

export const ASTEROID_SPAWN_PLAYER_SAFE_DISTANCE = 250;
export const SHIP_ASTEROID_COLLISION_COOLDOWN_MS = 750;
