export const TEAM_CAPACITY = 10;
export const TOTAL_PLAYER_CAPACITY = 20;
export const MAX_ROOM_CLIENTS = 40;

export const NETWORK_TICK_RATE = 20;
export const NETWORK_TICK_INTERVAL_MS = 1000 / NETWORK_TICK_RATE;
export const NETWORK_INPUT_TIMEOUT_MS = 300;

export const WORLD_WIDTH = 12000;
export const WORLD_HEIGHT = 12000;

export const RED_BASE_X = 760;
export const RED_BASE_Y = 760;
export const BLUE_BASE_X = WORLD_WIDTH - 760;
export const BLUE_BASE_Y = WORLD_HEIGHT - 760;

export const NETWORK_SHIP_MAX_SPEED = 500;
export const NETWORK_SHIP_ACCELERATION = 900;
export const NETWORK_SHIP_DECELERATION = 650;
export const NETWORK_SHIP_TURN_SPEED = 8;
export const NETWORK_SHIP_RADIUS = 58;
export const NETWORK_SHIP_MAX_HEALTH = 100;

export const NETWORK_PROJECTILE_DAMAGE = 15;
export const NETWORK_PROJECTILE_SPEED = 1200;
export const NETWORK_PROJECTILE_MAX_RANGE = 1400;
export const NETWORK_PROJECTILE_RADIUS = 14;
export const NETWORK_PROJECTILE_MUZZLE_OFFSET = 74;
export const NETWORK_WEAPON_FIRE_INTERVAL_MS = 180;
export const NETWORK_MAX_ACTIVE_PROJECTILES_PER_SHIP = 10;

export const NETWORK_RESPAWN_DELAY_MS = 3000;
export const NETWORK_SPAWN_INVULNERABILITY_MS = 2000;
